language: python
python:
    - 3.6
script:
- pip install twine
- python setup.py bdist_wheel

after_success:
    - echo [distutils]                                  > ~/.pypirc
    - echo index-servers =                             >> ~/.pypirc
    - echo "  pypi"                                    >> ~/.pypirc
    - echo                                             >> ~/.pypirc
    - echo [pypi]                                      >> ~/.pypirc
    - echo repository=https://upload.pypi.org/legacy/  >> ~/.pypirc
    - echo username=keyi                               >> ~/.pypirc
    - echo password=$PYPI_PASSWORD                     >> ~/.pypirc

deploy:
  provider: script
  script: /bin/sh .deploy.sh
  on:
    tags: true
    branch: master
